
###
post http://localhost:4000/teacher/login
Content-Type: application/json

{
    "username":"bharath",
    "password":"bharath"
}
###
put http://localhost:4000/teacher/update-class
Content-Type: application/json

{
    "name":"11",
    "students":["1101"],
    "concept":"MERN:concept delead today is MERN STACK"
}

###post
post http://localhost:4000/student/login
Content-Type: application/json

{
    "username":"satya",
    "password":"satya"
}

###
get http://localhost:4000/student/concepts
Content-Type: application/json

{
    "section":"31"
}
###
get http://localhost:4000/student/sec
